name: Build and Push Docker Image

on:
  push:
    branches: [ main, dev, feature/* ,fix-show-icon]

env:
  APP_VERSION: "1.0.3"
  ENABLE: "false"

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ env.ENABLE == 'true' }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/open-icon-repository:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/open-icon-repository:${{ env.APP_VERSION }}